// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var lastReading = LastReading.FromJson(jsonString);

namespace QuickType
{
	using System;
	using System.Collections.Generic;

	using System.Globalization;
	using Newtonsoft.Json;
	using Newtonsoft.Json.Converters;

	public partial class LastReading
	{
		[JsonProperty("sg")]
		public double Sg { get; set; }

		[JsonProperty("time")]
		public long Time { get; set; }

		[JsonProperty("id")]
		public string Id { get; set; }

		[JsonProperty("temp")]
		public double Temp { get; set; }

		[JsonProperty("type")]
		public string Type { get; set; }
	}

	public partial class LastReading
	{
		public static LastReading FromJson(string json) => JsonConvert.DeserializeObject<LastReading>(json, QuickType.Converter.Settings);
	}

	public static partial class Serialize
	{
		public static string ToJson(this LastReading self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
	}
}
